---
collections:
  - name: https://gitea.tryrocket.cloud/tryrocketcloud/homelab.git
    src: https://gitea.tryrocket.cloud/tryrocketcloud/homelab.git
    type: git
    version: main
  - community.healthchecksio
