name: Deployment

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: tryrocketcloud/workflows/.gitea/workflows/setup-runner.yaml@v0.0.4

  deploy:
    uses: tryrocketcloud/workflows/.gitea/workflows/deployment.yaml@v0.0.4
    secrets:
      ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            fc3a93f4-2a16-445b-b0c4-aeaf0102f0ff > SECRET_NAME_1
            bdbb16bc-0b9b-472e-99fa-af4101309076 > SECRET_NAME_2
