name: Hello

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  hello:
    runs-on: m700

    steps:
      - name: Run a script
        run: echo "This action runs every 2 minutes"
