name: Hello

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v2

      - name: Verify Just installation
        run: just --version

      - name: Run a script
        run: echo "This action runs every 2 minutes"
