name: Restart

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  restart:
    runs-on: self-hosted

    steps:
      - name: Restart
        run: echo "restart"

      - name: Restart Ansible
        run: ansible all \
          -m systemd \
          -a "name=invidious state=restarted scope=user" \
          -u invidious \
          -e "ansible_ssh_private_key_file=id_ed25519"
